In [2]:
%matplotlib inline
import numpy as np
from numpy import array
import pandas as pd
import sklearn
from sklearn import datasets
from sklearn import linear_model
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
plt.rcParams['figure.figsize']=(20.0,10.0)

In [3]:
data=datasets.load_boston()
print(data)

ImportError: 
`load_boston` has been removed from scikit-learn since version 1.2.

The Boston housing prices dataset has an ethical problem: as
investigated in [1], the authors of this dataset engineered a
non-invertible variable "B" assuming that racial self-segregation had a
positive impact on house prices [2]. Furthermore the goal of the
research that led to the creation of this dataset was to study the
impact of air quality but it did not give adequate demonstration of the
validity of this assumption.

The scikit-learn maintainers therefore strongly discourage the use of
this dataset unless the purpose of the code is to study and educate
about ethical issues in data science and machine learning.

In this special case, you can fetch the dataset from the original
source::

    import pandas as pd
    import numpy as np

    data_url = "http://lib.stat.cmu.edu/datasets/boston"
    raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
    data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
    target = raw_df.values[1::2, 2]

Alternative datasets include the California housing dataset and the
Ames housing dataset. You can load the datasets as follows::

    from sklearn.datasets import fetch_california_housing
    housing = fetch_california_housing()

for the California housing dataset and::

    from sklearn.datasets import fetch_openml
    housing = fetch_openml(name="house_prices", as_frame=True)

for the Ames housing dataset.

[1] M Carlisle.
"Racist data destruction?"
<https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8>

[2] Harrison Jr, David, and Daniel L. Rubinfeld.
"Hedonic housing prices and the demand for clean air."
Journal of environmental economics and management 5.1 (1978): 81-102.
<https://www.researchgate.net/publication/4974606_Hedonic_housing_prices_and_the_demand_for_clean_air>


In [ ]:
x=pd.DataFrame(data.data,columns=data.feature_names)
y=pd.DataFrame(data.target)
y

0
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [ ]:
x.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  506.000000  
mean    12.653063  
std      7.141062  
min      1.730000  
25%      6.950000  
50%     11.360000  
75%     16.955000  
max     37.970000

In [ ]:
reg=linear_model.LinearRegression()
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=7)


In [ ]:
reg.fit(x_train,y_train)

LinearRegression()

In [ ]:
y_pred=reg.predict(x_test)
print(y_pred)

[[23.01607649]
 [19.17545246]
 [19.93133255]
 [19.19222285]
 [ 4.73366059]
 [11.75829383]
 [21.13445607]
 [28.55636813]
 [29.15015547]
 [13.98488866]
 [ 6.11177952]
 [32.65621834]
 [18.81377591]
 [19.9985543 ]
 [37.32169943]
 [22.64542356]
 [29.02828657]
 [33.09225886]
 [10.54355651]
 [24.41353615]
 [21.10593843]
 [27.75398389]
 [37.57971161]
 [13.68016992]
 [ 9.13663239]
 [15.01638724]
 [35.69676984]
 [26.16279492]
 [25.59759605]
 [27.17821308]
 [18.96002469]
 [30.58940542]
 [31.32207069]
 [16.44852282]
 [39.65470263]
 [20.13979012]
 [18.89665346]
 [17.21466607]
 [21.63135449]
 [28.16696033]
 [26.95807073]
 [18.92203938]
 [14.39403714]
 [25.86680086]
 [18.36942302]
 [13.90509747]
 [24.99282465]
 [19.01042131]
 [20.59834287]
 [ 6.28489117]
 [27.71713116]
 [26.91042242]
 [12.16976487]
 [40.01902667]
 [14.76458951]
 [21.98077925]
 [20.19316318]
 [20.27107157]
 [23.6486951 ]
 [22.00151727]
 [20.75020815]
 [35.19539209]
 [17.48971422]
 [21.10693712]
 [23.91785914]
 [43.48010393]
 [19.50077

In [ ]:
print(y_test)

        0
357  21.7
337  18.5
327  22.2
13   20.4
418   8.8
..    ...
413  16.3
408  17.2
80   28.0
451  15.2
26   16.6

[102 rows x 1 columns]


In [ ]:
#Accuracy using Mean Squared Error
MSE=np.mean((y_pred-y_test)**2)
print(MSE)

0    34.056481
dtype: float64


In [ ]:

from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

34.056481348874414


In [ ]:
y_p=reg.predict([[0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98]])
print(y_p)

[[29.58950356]]


In [ ]:
#R squared Value
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred)*100)

57.85415472763433


In [ ]:
reg.coef_

array([[-1.24649091e-01,  3.04735052e-02,  2.17990089e-02,
         2.79225761e+00, -1.52135247e+01,  5.27249266e+00,
        -1.10577742e-02, -1.27320872e+00,  2.65804711e-01,
        -1.15043029e-02, -9.19571148e-01,  1.01624292e-02,
        -3.89712044e-01]])

In [ ]:
reg.intercept_

array([23.55424547])